### ISSUE TITLE
Refresh Suppliers, Programs, Accounts

### ISSUE THREAD

**Issue by adsuttie** [Bwian/pops#123]
Our accounts team needs to be able to refresh POPS tables when they add a supplier. They are generally marked as Processors. Is it possible for them to see the Refresh buttons including Suppliers, Programs, Accounts, Payment Terms, Tax Rates?

**Comment by Bwian** [comment]
Why don't you just give them admin access?  The only extra functionality that would give them over and above being able to maintain the Exo tables is to maintain the delivery addresses (probably desirable anyway) and modify users which is a little academic given that they are added automagically anyway.  It would mean they could change user permissions, though.

I'll close it on the assumption this solution will be OK.  Feel free to reopen it if it's not!
