### ISSUE TITLE
Order 5367 is stuck in Draft. Admin can not delete.

### ISSUE THREAD

**Issue by adsuttie** [Bwian/pops#124]
ckemp has created a draft order that now needs to be deleted. Usually admin can delete unprocessed orders but only the Print option is available.

**Comment by Bwian** [comment]
This is as designed - see [here](https://github.com/Bwian/pops/wiki/Edit-Purchase-Order) - but can probably be changed if needed.  You would need to give a bit of thought to what an administrator can do in that circumstance, though.  The routine code that checks the permissions is generic, so giving an admin user the ability delete an order will currently give them permission to do everything else too - edit, submit etc.  At the moment there is no separate flag to say who submitted it and it wouldn't currently be tracked in notes so it would look like it was submitted by the person who drafted it even though it was actually the administrator.

As it is at the moment, ckemp should be able to delete it herself or submit it after which the approver will be able to delete it.  Reopen the issue if there's a reason this won't work or if you want to change the admin functionality.  Alternatively, I can delete it manually with SQL but that's probably not the best idea as there will be no audit trail.
