### ISSUE TITLE
Email reminders

### ISSUE THREAD

**Issue by adsuttie** [Bwian/pops#128]
We are finding that unprocessed purchase orders are banking up in POPS. Is it possible to send reminder emails to owners summarising anything over 1 month old in the following categories with links to the orders?
(a) Draft - Waiting for you to Submit or Delete if no longer required.
(b) Submitted - Waiting for Approval or Delete if no longer required.
(c) Approved - The Accounts Department is waiting to receive the invoice for this order.

**Comment by Bwian** [comment]
So, by "owners" do you mean the person who created them?  And how do you want to trigger the emails?

**Comment by adsuttie** [comment]
I think it would be good to have the Creators receive the notification as they are more likely to know the status of the item or order and push it along or delete it.

Maybe on the 15th day of each month everyone gets a reminder about orders in these categories dated before the 15th of the previous month. Does that sound reasonable?

Kind Regards,

Adrian Suttie
Finance Manager
UnitingCare Ballarat Parish Mission
105 Dana Street Ballarat 3350
t  (03) 5322 4934  |  f  (03) 5332 1055
e  asuttie@ucare.org.au<mailto:asuttie@ucare.org.au>
w  www.unitingcareballarat.com.au<http://www.unitingcareballarat.com.au/>

**Comment by Bwian** [comment]
Individual emails done and summary for POPS administrator but explanations of what to do depending on status not included.  Minor rework required to include this.

**Comment by Bwian** [comment]
Further rework performed to group all orders for one user in a single email.  Details of the implementation can be found [here.](../wiki/Email-order-reminders)
