### ISSUE TITLE
Error on Approve

### ISSUE THREAD

**Issue by adsuttie** [Bwian/pops#132]
POPS is producing an error on approval.

I tested a new order #5880. The status has been updated to approved but I did not receive an email and got an error message "If you are the application owner check the logs for more information."

I hope it isn't but the error may be associated with the Joomla hack. Anders restored the home page backup and is going to upgrade the version.

**Comment by Bwian** [comment]
I think the problem is that they bounced the server but didn't restart the mail service, postfix.

I've restarted it manually but you need to ask Viatek to include it when it reboots.  Not sure how this works on ubuntu.

**Comment by Bwian** [comment]
Reopening this to try and trap and report the error rather than have it fail silently or goto the 500 page as it does at the moment.  If the mail service isn't running, Errno::ECONNREFUSED is raised but only in the production environment.

**Comment by Bwian** [comment]
Viatek have included postfix in the startup list.

**Comment by Bwian** [comment]
Error trapped and "Mail service not running" reported to user instead of 500 error.
