### ISSUE TITLE
Account field does not allow typing to search when filter is on

### ISSUE THREAD

**Issue by adsuttie** [Bwian/pops#134]
The account field does not act the same as the Program field and does not immediately allow typing after a Program has been selected. Response is inconsistent:
- Clicking straight into Account without selecting a Program works as expected
- After selecting a Program the Account field does not immediately allow typing. Backspace takes the user back to the Order Details screen
- Double clicking on the Account field allows typing.

The issue here is just the inconsistency and the annoyance of pressing backspace which usually deletes the account description and allows typing but sometimes goes back to the previous screen.

**Comment by Bwian** [comment]
Can't reproduce this in Chrome, Safari or Microsoft Edge.  Check next time in the office.

**Comment by Bwian** [comment]
Couldn't reproduce this in the office either.  Adrian to further experiment with it.

**Comment by Bwian** [comment]
Adrian can no longer reproduce this either.  Closed.
