### ISSUE TITLE
Add Receipting step to workflow

### ISSUE THREAD

**Issue by Bwian** [Bwian/pops#136]
To enforce the use of POs, a receipting step is needed between the approval and processing steps.  This will confirm that goods or services have been received before payments are processed.  The following restrictions apply:
- the person creating the PO will not necessarily be the person receipting it
- the person approving the PO cannot receipt it

Target date - November

**Comment by Bwian** [comment]
Done some work on the data model for this, adding receiver_id and received_at columns to database and started working on state changes.  

A couple of questions for Danni:
- Is describing the state as "Received" OK or do you want to use "Receipted"?
- Are there ever going to be circumstances where the approved amount doesn't match the invoiced amount?  If so, how do you want to handle over and under payments?

**Comment by DanniW** [comment]
Thanks Brian
In terms of wording - not fussed - probably "Received" is best
As for non-matching you are right we will need to be able to "part" receive.  So as long as the invoice is not for more than the received amount I think this will be fine.

**Comment by Bwian** [comment]
At the moment I've added the columns to handle receipting to the orders table.  We could probably add an outstanding balance column to orders as well but I'm beginning to think that it might be better to bite the bullet and add a seperate receipts table.  This could track who and when, the value of the goods received and a description for use if the total doesn't match that of the order.  It makes the receipting process a little more than just pushing a button but we can default all the fields so most of the time they won't need to do more than press OK.

This  would form the basis of the [Blanket Purchase Orders](./138) functionality too.

**Comment by DanniW** [comment]
Yes - this sounds like the best option...  how hard is this to do?

**Comment by Bwian** [comment]
Shouldn't be too bad for the majority of cases where the order total matches the invoice.  The tricky bit is, as always, the edge cases.  eg. Assuming normal orders as opposed to blanket ones, when the invoice total is less than the order do you:
- flag the order as Received so that it can be processed?  If you do, how does the order get changed and authorised so that the new amount ends up in EXO?
- not allow it to be Received unless the amounts match?  This might mean adding a "write-off" receipt record (not the right terminology but you know what I mean) to make the totals match.  This will still leave the problem of getting the right amount into EXO, though.
- flag it as Received and let the processor sort it out.  Your staff must come across this scenario now - how do they handle it?
- allow partial payments?  I can imagine a situation where one of the items is on back order but you need to pay for the goods received.  Again, how do they handle it now?
And what do we do when the invoice total is higher than the order total?  Change the order and resubmit it for approval?  Or something different?
Have a think about these and I'll give you a call to discuss it further.

**Comment by Bwian** [comment]
Proposed implementation notes can be found [here](../wiki/Receiving).  This handles most of the issues identified previously.  See [this issue](./140) for the proposed changes to the Processing workflow.

**Comment by DanniW** [comment]
Thanks Brian - on the order is fine

**Comment by Bwian** [comment]
Need invoice number entered in processing step for blanket POs, passed to EXO and stored in notes.

**Comment by Bwian** [comment]
Invoice number field left active and moved to last field on form if current action is processing.  Still to do:
- ensure invoice_no change is being tracked
- ensure notes records written during processing step
- add received total to order summary and adjust total accordingly
- look at receipts breakdown against items or maybe just total

**Comment by Bwian** [comment]
Completed but still need to change processing functionality (#140)
