### ISSUE TITLE
Processing Orders outside current GL Period

### ISSUE THREAD

**Issue by Bwian** [Bwian/pops#139]
The PO invoice date determines the period to which the completed order is posted in EXO.  If the period is closed, the invoice date needs to be manually changed in EXO to ensure correct posting.

Need to be able to limit invoice date to a date in an open period in EXO.  Considerations include:
- ideally, allowable dates should be determined by interrogation of EXO 
- at EOM, there may be two periods open
- is invoice date the date that we should be using?  Probably need to store the invoice date from the supplier's invoice and add another date column to pass to EXO
- we can check that the invoice date falls within an open period when the PO is created but the period will not necessarily still be open when the PO is processed so need to check again before it is sent to EXO.
- if we can't get the period information from EXO, we may need to add a configuration variable which stores the date cutoff.  This would need to be manually maintained by accounts staff but we may be able to build some smarts into it to check that the date is set sensibly
- PO payment date is no longer used by the accounts staff

**Comment by DanniW** [comment]
Thanks Brian - this looks fine

**Comment by Bwian** [comment]
Looks like we can get this information from EXO without too much trouble using:
- select min(STARTDATE) from [PERIOD_STATUS] where LEDGER = 'C' and LOCKED = 'N'
- select max(STOPDATE) from [PERIOD_STATUS] where LEDGER = 'C' and LOCKED = 'N'

A few questions:
- Should I be looking at the GL period (G) or Creditor period (C)?  It look like these will usually be the same but who knows
- Can I assume that any open periods will be consecutive?  i.e. as of today (6/11) the above queries return a start date of 1/10 and an end date of 30/11.
- If not, will you ever need to create invoices in anything other than the last two periods?
- Do I need to check the stop date?  What will happen in EXO if you try to create an invoice in a future period that doesn't have a PERIOD_STATUS record yet?

-

**Comment by DanniW** [comment]
1. It would be the same - we would normally close of GL and Creditors at the same time.
2.  Yes
3. N/A
4. Yes - ideally if we can stop future dated invoices in closed periods that would be ideal.
5.  Just before processing
6. As POPs regularly times-out I think that validation on login would be sufficient.
Thanks - let us know if you have any further questions.

**Comment by Bwian** [comment]
Complete and prototype code tested successfully against EXO_TEST.
